# Generated by Django 2.2.11 on 2020-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociostudents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default='I am loving SocioStudent'),
        ),
    ]
