# Generated by Django 2.2.11 on 2020-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociostudents', '0002_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='gren@ninja.com', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='shuriken', max_length=100),
        ),
    ]
